doc-valid-idents = ["UniFFI", "GeoJSON", ".."]

[[disallowed-methods]]
path = "std::iter::Iterator::for_each"
reason = "for_each is to Iterator what an initializer is for a type (F-PURE-MUT)"

[[disallowed-methods]]
path = "std::iter::Iterator::try_for_each"
reason = "try_for_each is to Iterator what an initializer is for a type (F-PURE-MUT)"
